set_property SRC_FILE_INFO {cfile:c:/Users/u39jm15/AppData/Roaming/Xilinx/Vivado/Projects/SSL_Peak_Extract_Repo/project_1/project_1.gen/sources_1/ip/cordic_0/cordic_0/cordic_0_in_context.xdc rfile:../../../../../project_1.gen/sources_1/ip/cordic_0/cordic_0/cordic_0_in_context.xdc id:1 order:EARLY scoped_inst:extract_peak/square_root_photon_count} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/u39jm15/AppData/Roaming/Xilinx/Vivado/Projects/SSL_Peak_Extract_Repo/project_1/project_1.gen/sources_1/ip/cordic_0/cordic_0/cordic_0_in_context.xdc rfile:../../../../../project_1.gen/sources_1/ip/cordic_0/cordic_0/cordic_0_in_context.xdc id:2 order:EARLY scoped_inst:extract_second_peak/square_root_photon_count} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/u39jm15/AppData/Roaming/Xilinx/Vivado/Projects/SSL_Peak_Extract_Repo/project_1/project_1.gen/sources_1/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc rfile:../../../../../project_1.gen/sources_1/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc id:3 order:EARLY scoped_inst:depth_extraction/divide} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/u39jm15/AppData/Roaming/Xilinx/Vivado/Projects/SSL_Peak_Extract_Repo/project_1/project_1.gen/sources_1/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc rfile:../../../../../project_1.gen/sources_1/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc id:4 order:EARLY scoped_inst:second_depth_extraction/divide} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/u39jm15/AppData/Roaming/Xilinx/Vivado/Projects/SSL_Peak_Extract_Repo/project_1/project_1.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:5} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells extract_peak/square_root_photon_count]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells extract_second_peak/square_root_photon_count]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1000 [get_pins depth_extraction/divide/aclk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells depth_extraction/divide]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1000 [get_pins second_depth_extraction/divide/aclk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells second_depth_extraction/divide]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells extract_peak/square_root_photon_count]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells extract_second_peak/square_root_photon_count]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells depth_extraction/divide]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells second_depth_extraction/divide]
